#  Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
#  See https://llvm.org/LICENSE.txt for license information.
#  SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#  Copyright (c) 2024.

name: Auto bump LLVM
on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/bump_llvm.yml"
  schedule:
    # At minute 0 past hour 1. (see https://crontab.guru)
    - cron: '00 01 * * *'
jobs:
  update-dep:

    name: "Bump LLVM and send PR"

    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: "Check out repository"
        uses: actions/checkout@v4.2.2
        with:
          submodules: true

      - name: "Sync third-party/llvm-project"
        id: sync-llvm-project
        run: |
          pushd third_party/llvm-project
          git checkout main && git pull
          echo "LLVM_SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          popd

      - uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ secrets.BUMP_LLVM_CREATE_PR_APP_ID }}
          private-key: ${{ secrets.BUMP_LLVM_CREATE_PR_APP_PRIVATE_KEY }}

      - name: "Create Pull Request"
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: "[LLVM] Bump to ${{ steps.sync-llvm-project.outputs.LLVM_SHA_SHORT }}"
          title: "[LLVM] Bump to ${{ steps.sync-llvm-project.outputs.LLVM_SHA_SHORT }}"
          body: "Bump LLVM to https://github.com/llvm/llvm-project/commit/${{ steps.sync-llvm-project.outputs.LLVM_SHA_SHORT }}"
          author: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
          base: main
          branch: update-llvm
          delete-branch: true
          assignees: makslevental
          reviewers: makslevental

      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ steps.generate-token.outputs.token }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
          
      - name: Auto approve
        run: gh pr review --approve "${{ steps.cpr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
